apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp:
  labels:
    app: spiderfoot
  name: spiderfoot-gke-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spiderfoot
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        app: spiderfoot
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/IMAGE:TAG
        name: spiderfoot-container
