apiVersion: v1
kind: Service
metadata:
  name: spiderfoot-service
spec:
  type: LoadBalancer
  ports:
    - name: webapp
      port: 5001
  selector:
    app: spiderfoot

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: spiderfoot
