name: container-analysis

on:
  release:
    types: [push]
 
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: sast
    runs-on: ubuntu-18.04
    steps:
    # Setup gcloud CLI
    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }} 
    - run: |-
        gcloud --quiet beta container images describe 'gcr.io/mythic-inn-323010/spiderfoot-img:"sha256":<f84e2bcf622f1bb471b3117e327af8c4f3c525353a910ce9ec6ad3e6b192dc44>' --show-package-vulnerability > scanreport.txt
    - uses: actions/upload-artifact@v2
      with:
        path: scanreport.txt
